name: tank_robot_environment

dependencies:
  - python=3.8.10
  - pip
  - pip:
    - xacro==1.14.18
    - urdfdom-py==0.4.6
    - unique-id==1.0.6
    - turtlebot3-teleop==1.2.5
    - turtlebot3-example==1.2.5
    - topic-tools==1.17.0
    - tf2-ros==0.7.7
    - tf2-py==0.7.7
    - tf2-kdl==0.7.7
    - tf2-geometry-msgs==0.7.7
    - tf==1.13.2
    - srdfdom==0.6.4
    - smclib==1.8.6
    - sensor-msgs==1.13.1
    - rviz==1.14.25
    - rqt-web==0.4.10
    - rqt-topic==0.4.13
    - rqt-top==0.4.10
    - rqt-tf-tree==0.6.4
    - rqt-srv==0.4.9
    - rqt-shell==0.4.11
    - rqt-service-caller==0.4.10
    - rqt-rviz==0.7.0
    - rqt-runtime-monitor==0.5.10
    - rqt-robot-steering==0.5.12
    - rqt-robot-monitor==0.5.15
    - rqt-robot-dashboard==0.5.8
    - rqt-reconfigure==0.5.5
    - rqt-py-trees==0.4.1
    - rqt-py-console==0.4.10
    - rqt-py-common==0.5.3
    - rqt-publisher==0.4.10
    - rqt-pr2-dashboard==0.4.1
    - rqt-pose-view==0.5.11
    - rqt-plot==0.4.13
    - rqt-nav-view==0.5.7
    - rqt-multiplot==0.0.12
    - rqt-msg==0.4.10
    - rqt-moveit==0.5.11
    - rqt-logger-level==0.4.12
    - rqt-launch==0.4.9
    - rqt-joint-trajectory-controller==0.22.0
    - rqt-image-view==0.4.17
    - rqt-gui==0.5.3
    - rqt-gui-py==0.5.3
    - rqt-ground-robot-teleop==1.4.2
    - rqt-graph==0.4.14
    - rqt-ez-publisher==0.6.1
    - rqt-drone-teleop==1.4.2
    - rqt-dep==0.4.12
    - rqt-controller-manager==0.20.0
    - rqt-console==0.4.12
    - rqt-bag==0.5.1
    - rqt-bag-plugins==0.5.1
    - rqt-action==0.4.9
    - roswtf==1.17.0
    - rosunit==1.15.8
    - rostopic==1.17.0
    - rostest==1.17.0
    - rosservice==1.17.0
    - rosserial-python==0.9.2
    - rosserial-client==0.9.2
    - rosserial-arduino==0.9.2
    - rospy==1.17.0
    - rosparam==1.17.0
    - rosnode==1.17.0
    - rosmsg==1.17.0
    - rosmaster==1.17.0
    - roslz4==1.17.0
    - roslint==0.12.0
    - roslib==1.15.8
    - roslaunch==1.17.0
    - rosgraph==1.17.0
    - rosclean==1.15.8
    - rosbag==1.17.0
    - resource-retriever==1.12.7
    - qt-gui==0.4.2
    - qt-gui-py-common==0.4.2
    - qt-gui-cpp==0.4.2
    - qt-dotgraph==0.4.2
    - python-qt-binding==0.4.4
    - py-trees==0.7.6
    - pr2-power-board==1.1.10
    - message-filters==1.17.0
    - mavros==1.20.0
    - laser-geometry==1.6.7
    - joint-state-publisher==1.15.1
    - joint-state-publisher-gui==1.15.1
    - interactive-markers==1.12.0
    - image-geometry==1.16.2
    - genpy==0.6.15
    - gennodejs==2.0.2
    - genmsg==0.6.0
    - genlisp==0.4.18
    - geneus==3.0.0
    - gencpp==0.7.0
    - gazebo-ros==2.9.2
    - gazebo-plugins==2.9.2
    - dynamixel-sdk==3.7.51
    - dynamic-reconfigure==1.7.3
    - drone-wrapper==1.4.2
    - diagnostic-updater==1.11.0
    - cv-bridge==1.16.2
    - controller-manager==0.20.0
    - controller-manager-msgs==0.20.0
    - catkin==0.8.10
    - camera-calibration-parsers==1.12.0
    - base-local-planner==1.17.3
    - angles==1.9.13
    - actionlib==1.14.0
    - zipp==3.20.2
    - yarl==1.15.2
    - wslink==2.2.1
    - widgetsnbextension==4.0.13
    - wcwidth==0.2.13
    - vtk==9.3.1
    - typing-extensions==4.12.2
    - trame==3.7.1
    - trame-server==3.2.3
    - trame-client==3.5.0
    - traitlets==5.14.3
    - tornado==6.4.2
    - stack-data==0.6.3
    - scooby==0.10.0
    - scipy==1.10.1
    - pyzmq==26.2.0
    - pyvista==0.44.2
    - python-dateutil==2.9.0.post0
    - pygments==2.18.0
    - pure-eval==0.2.3
    - propcache==0.2.0
    - prompt-toolkit==3.0.48
    - pooch==1.8.2
    - platformdirs==4.3.6
    - pickleshare==0.7.5
    - parso==0.8.4
    - numpy==1.24.4
    - nest-asyncio==1.6.0
    - multidict==6.1.0
    - msgpack==1.1.0
    - matplotlib-inline==0.1.7
    - jupyterlab-widgets==3.0.13
    - jupyter-core==5.7.2
    - jupyter-client==8.6.3
    - jedi==0.19.2
    - ipywidgets==8.1.5
    - ipython==8.12.3
    - ipykernel==6.29.5
    - importlib-metadata==8.5.0
    - frozenlist==1.5.0
    - executing==2.1.0
    - debugpy==1.8.11
    - comm==0.2.2
    - backcall==0.2.0
    - async-timeout==5.0.1
    - asttokens==3.0.0
    - aiosignal==1.3.1
    - aiohttp==3.10.11
    - aiohappyeyeballs==2.4.4
    - zope.interface==4.7.1
    - xkit==0.0.0
    - wstool==0.1.18
    - wsaccel==0.6.2
    - wrapt==1.11.2
    - wheel==0.34.2
    - webencodings==0.5.1
    - wadllib==1.3.3
    - vcstools==0.1.42
    - urllib3==1.25.8
    - unattended-upgrades==0.1
    - ufw==0.36
    - ubuntu-pro-client==8001
    - ubuntu-drivers-common==0.0.0
    - u-msgpack-python==2.1
    - txaio==2.10.0
    - Twisted==18.9.0
    - termcolor==1.1.0
    - systemd-python==234
    - ssh-import-id==5.10
    - soupsieve==1.9.5
    - sos==4.7.2
    - six==1.14.0
    - sip==4.19.21
    - simplejson==3.16.0
    - setuptools==45.2.0
    - service-identity==18.1.0
    - SecretStorage==2.3.1
    - rospkg==1.5.1
    - rospkg-modules==1.5.1
    - rosinstall==0.7.8
    - rosinstall-generator==0.1.23
    - rosdistro==1.0.1
    - rosdistro-modules==1.0.1
    - rosdep==0.25.1
    - rosdep-modules==0.25.1
    - roman==2.0.0
    - requests==2.22.0
    - requests-unixsocket==0.2.0
    - PyYAML==5.3.1
    - pytz==2019.3
    - PyTrie==0.2
    - python-snappy==0.5.3
    - python-gnupg==0.4.5
    - python-gitlab==2.0.1
    - python-debian==0.1.36+ubuntu1.1
    - python-apt==2.0.1+ubuntu0.20.4.1
    - pyserial==3.4
    - pyrsistent==0.15.5
    - pyRFC3339==1.1
    - PyQt5==5.14.1
    - PyQRCode==1.2.1
    - pypng==0.0.20
    - pyparsing==2.4.6
    - pyOpenSSL==19.0.0
    - PyOpenGL==3.1.0
    - PyNaCl==1.3.0
    - pymacaroons==0.13.0
    - PyJWT==1.7.1
    - PyHamcrest==1.9.0
    - pygraphviz==1.5
    - PyGObject==3.36.0
    - PyGithub==1.43.7
    - pydot==1.4.1
    - pycups==1.9.73
    - pycryptodomex==3.6.1
    - pycairo==1.16.2
    - pyassimp==4.1.4
    - pyasn1==0.4.2
    - pyasn1-modules==0.2.1
    - py-ubjson==0.14.0
    - psutil==5.5.1
    - protobuf==3.6.1
    - pip==20.0.2
    - Pillow==7.0.0
    - pexpect==4.6.0
    - paramiko==2.6.0
    - packaging==20.3
    - osrf-pycommon==2.0.2
    - olefile==0.46
    - oauthlib==3.1.0
    - nose==1.3.7
    - netifaces==0.10.4
    - mpi4py==3.0.3
    - more-itertools==4.2.0
    - matplotlib==3.1.2
    - MarkupSafe==1.1.0
    - macaroonbakery==1.3.1
    - lz4==3.0.2+dfsg
    - lxml==4.5.0
    - lazr.uri==1.0.3
    - lazr.restfulclient==0.14.2
    - launchpadlib==1.10.13
    - language-selector==0.1
    - kiwisolver==1.0.1
    - keyring==18.0.1
    - jsonschema==3.2.0
    - jsonpointer==2.0
    - jsonpatch==1.22
    - Jinja2==2.10.1
    - incremental==16.10.1
    - idna==2.8
    - hyperlink==19.0.0
    - httplib2==0.14.0
    - html5lib==1.0.1
    - gpg==1.13.1
    - fastimport==0.9.8
    - entrypoints==0.3
    - empy==3.3.2
    - dulwich==0.19.15
    - docutils==0.16
    - distro==1.4.0
    - distro-info==0.23+ubuntu1.1
    - Deprecated==1.2.7
    - defusedxml==0.6.0
    - defer==1.0.6
    - decorator==4.4.2
    - dbus-python==1.2.16
    - Cython==0.29.14
    - cycler==0.10.0
    - cupshelpers==1.0
    - cryptography==2.8
    - constantly==15.1.0
    - configobj==5.0.6
    - command-not-found==0.3
    - colorama==0.4.3
    - cloud-init==24.3.1
    - Click==7.0
    - chardet==3.0.4
    - certifi==2019.11.28
    - cbor==1.0.0
    - catkin-tools==0.9.4
    - catkin-pkg==1.0.0
    - catkin-pkg-modules==1.0.0
    - breezy==3.0.2
    - blinker==1.4
    - beautifulsoup4==4.8.2
    - bcrypt==3.1.7
    - Automat==0.8.0
    - autobahn==17.10.1
    - attrs==19.3.0