  type        : "diff_drive_controller/DiffDriveController"

  # left_wheel  : ['front_left_wheel_joint', 'rear_left_wheel_joint', 'middle1_left_wheel_joint', 'middle2_left_wheel_joint']
  # right_wheel : ['front_right_wheel_joint', 'rear_right_wheel_joint', 'middle1_right_wheel_joint', 'middle2_right_wheel_joint']

  left_wheel: ['middle1_left_wheel_joint', middle2_left_wheel_joint]
  right_wheel: ['middle1_right_wheel_joint', middle2_right_wheel_joint]
  wheel_separation : 0.29 #0.095
  wheel_radius : 0.0414

  wheel_separation_multiplier: 10.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  base_frame_id: base_link #default: base_link
  odom_frame_id: odom


  publish_rate: 50.0               # default: 50
  # cmd_vel_topic: '/tank_diff_drive_controller/cmd_vel'
  odom_topic: '/odom'
  publish_cmd: true
  publish_odom: false
  enable_odom_tf: false
  use_stamped_vel: false
  # cmd_vel_timeout: 0.25
  # velocity_rolling_window_size: 10
  estimate_velocity_from_position: false

  # pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  # twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  pose_covariance_diagonal: [0.001, 0.001, 
                             0.001, 0.001, 
                             0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 
                              0.001, 0.001, 
                              0.001, 0.03]

  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5
  
  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.5  # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.8  # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.0  # rad/s^2