type: joint_state_controller/JointStateController
publish_rate: 50

gazebo_ros_control:
  pid_gains:
    middle1_left_wheel_joint: #{p: 100.0, i: 0.0, d: 10.0}
      p: 100.0
      i: 0.01
      d: 10.0
    middle2_left_wheel_joint: #{p: 100.0, i: 0.0, d: 10.0}
      p: 100.0
      i: 0.01
      d: 10.0  
    middle1_right_wheel_joint: #{p: 100.0, i: 0.0, d: 10.0}
      p: 100.0
      i: 0.01
      d: 10.0
    middle2_right_wheel_joint: #{p: 100.0, i: 0.0, d: 10.0}
      p: 100.0
      i: 0.01
      d: 10.0
